version: '2'

services:
  orders:
    image: crshanks/sock-shop-orders-nr:1.0
    hostname: orders
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-javaagent:/agent.jar -Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
      - NEW_RELIC_LICENSE_KEY
      - NEW_RELIC_APP_NAME="sock-shop-orders"
      - NEW_RELIC_LOG_FILE_NAME=STDOUT
      - NEW_RELIC_CA_BUNDLE_PATH=DOES_NOT_EXISTS
      - NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true
