version: '2'

services:
  front-end:
    image: crshanks/sock-shop-front-end-nr:1.0
    hostname: front-end
    restart: always
    cap_drop:
      - all
    read_only: true
    environment:
      - NEW_RELIC_LICENSE_KEY
      - NEW_RELIC_NO_CONFIG_FILE=true
      - NEW_RELIC_APP_NAME=sock-shop-front-end
      - NEW_RELIC_LOG=stdout
      - NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true